name: Github Action Test
on:
  issues:

jobs:
  job1:
    name: Echo
    runs-on: macos-latest
    steps:
      - run: echo 'Hello GDSC!'
  job2:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -al
