name: Github Action Test
on:
  push:
    branches: [master]
jobs:
  job1:
    name: Echo
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello GDSC!'
  job2:
    name: PWD & LS
    runs-on: macos-latest
    steps:
      - run: pwd
      - run: ls -al
